AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ReInvent2018CFNLTNov27-1
      LaunchTemplateData:
        ImageId: ami-0922553b7b0369273
        InstanceType: t2.micro
        UserData: !Base64
          Fn::Sub: |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
            yum install -y httpd mariadb-server
            systemctl start httpd
            systemctl enable httpd
            usermod -a -G apache ec2-user
            chown -R ec2-user:apache /var/www
            chmod 2775 /var/www
            find /var/www -type d -exec chmod 2775 {} \;
            find /var/www -type f -exec chmod 0664 {} \;
            echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
        SecurityGroupIds:
          - sg-025def4d7af8d3d23
        CreditSpecification:
          CpuCredits: standard  
  CFNLTAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Reinvent2018CFNASGNov27-2
      LaunchTemplate:
        LaunchTemplateId:
          !Ref ASGLaunchTemplate
        Version:
          !GetAtt ASGLaunchTemplate.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      VPCZoneIdentifier:
        - subnet-031cc93d
